name = "nuxt-split-workers-test"
main = ".output/server/index.mjs"
compatibility_date = "2023-05-09"

base_dir = ".output/server"

find_additional_modules = true
rules = [
  { type = "CommonJS", globs = ["**/*.cjs"]},
  { type = "ESModule", globs = ["**/*.js", "**/*.mjs"]},
]

[site]
bucket = ".output/public"